# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=256)),
                ('quiz_description', models.CharField(max_length=256)),
                ('quiz_time', models.IntegerField()),
                ('per_question_marks', models.IntegerField()),
                ('quiz_status', models.BooleanField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('difficulty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.DifficultyData')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.QuestionData')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizData')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestionResponseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_flag', models.BooleanField(default=False)),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.OptionData')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.QuestionData')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizData')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResponseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizData')),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentData')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSubjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_questions', models.IntegerField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizData')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.SubjectData')),
            ],
        ),
    ]
